apiVersion: v1
data:
  tls.crt: ""
  tls.key: ""
kind: Secret
metadata:
  name: cass-operator-webhook-config
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: "cassandradatacenter-webhook-registration"
webhooks:
- name: "cassandradatacenter-webhook.cassandra.datastax.com"
  rules:
  - apiGroups:   ["cassandra.datastax.com"]
    apiVersions: ["v1beta1"]
    operations:  ["CREATE", "UPDATE", "DELETE"]
    resources:   ["cassandradatacenters"]
    scope:       "*"
  clientConfig:
    service:
      name: "cassandradatacenter-webhook-service"
      namespace: "demo"
      path: /validate-cassandra-datastax-com-v1beta1-cassandradatacenter
  admissionReviewVersions: ["v1beta1"]
  failurePolicy: "Ignore"
  matchPolicy: "Equivalent"
  sideEffects: None
  timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cassandradatacenter-webhook-service
  namespace: "demo"
  labels:
    name: cass-operator-webhook
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    name: cass-operator
